#!/bin/sh

# This is a setup script for my own web server. Feel free to ignore

git pull origin master

cd dominion_web
echo "Building client-side web code..."
pub get
pub build

cd ../dominion_server
echo "Fetching server dependencies..."
pub get
