name: 'dominion_web'
version: 0.0.1
description: An absolute bare-bones web app.

environment:
  sdk: '>=2.3.0-dev.0 <3.0.0'

dependencies:
  crypto: ^2.0.6

dev_dependencies:
  sass_builder: ^2.1.2
  build_runner: any
  build_web_compilers: any
