name: dominion_core
description: Core Dominion engine
version: 0.0.1
#author: Jack Thakar <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.13.0 <2.0.0'
  
dev_dependencies:
  test: ^0.12.5
