name: 'dominion_server'
version: 0.0.1

environment:
  sdk: '>=1.13.0 <2.0.0'

dependencies:
  http_server: "^0.9.6"
  dominion_core:
    path: "../dominion_core"
  dominion_sets:
    path: "../dominion_sets"
