name: 'dominion_server'
version: 0.0.1

environment:
  sdk: '>=2.3.0-dev.0.5.flutter-a1668566e5 <3.0.0'

dependencies:
  http: ^0.12.0+2
  http_server: "^0.9.8+1"
  web_socket_channel: ^1.0.12
  dominion_core:
    path: "../dominion_core"
  dominion_sets:
    path: "../dominion_sets"
